### ISSUE TITLE
Can't use rebound omnicomplete

### ISSUE THREAD

**Issue by timshannon** [rhysd/NyaoVim#35]
My omnicomplete remap is below.  It doesn't seem to work from within nyaoVim, but it works fine in the terminal.  Is electron grabbing the ctrl modifiers somehow?

```
inoremap <expr> <C-Space> pumvisible() \|\| &omnifunc == '' ?
\ "\<lt>C-n>" :
\ "\<lt>C-x>\<lt>C-o><c-r>=pumvisible() ?" .
\ "\"\\<lt>c-n>\\<lt>c-p>\\<lt>c-n>\" :" .
\ "\" \\<lt>bs>\\<lt>C-n>\"\<CR>"
imap <C-@> <C-Space>
set completeopt=menuone,longest
```

**Comment by rhysd** [comment]
Let me ask a question.  Both `<C-Space>` and `<C-@>` don't work?  I want to know which part doesn't work properly.

**Comment by rhysd** [comment]
NyaoVim seems to fail handling `<C-@>` and `<C-Space>`.  I'm investigating.

**Comment by rhysd** [comment]
I fixed this in https://github.com/rhysd/NyaoVim/issues/35.  Please reinstall `nyaovim` to update `neovim-component` module.

**Comment by zhranklin** [comment]
I have reinstall nyaovim but the problem is still there. @rhysd

**Comment by rhysd** [comment]
I confirmed both `<C-Space>` and `<C-@>` seem to work in my environment with the latest version (neovim-component v0.6.1).

If you notice the bug is still there, please ping me here to reopen this issue.
