### ISSUE TITLE
Only blank window shown when launching

### ISSUE THREAD

**Issue by deto** [rhysd/NyaoVim#53]
### Expected Behavior

When running nyaovim from the command prompt, only a blank window is launched.  Does not respond to input.

### Actual Behavior

NyaoVim launches as expected

### Steps to Reproduce (including precondition)

Install NyaoVim using "npm install -g nyaovim".  Open a command prompt and type nyaovim<cr>

### Screenshot on This Problem (if possible)

{Please write here}

### Your Environment

- OS: {Windows 10, Build 14342}
- NyaoVim version: {0.0.19}
- `nvim` version: {0.1.5-dev}
- Keyboard layout: {qwerty}
- Linux: Window manager: {N/A}

### Additional Comments (if any)

Neovim-qt works as expected.  Using the MSVC 2015 - compiled version of nvim  (the MSYS version wouldn't work with neovim-qt or nyaovim)

**Comment by gosukiwi** [comment]
Same here. Using Windows 10 14352 insider build

**Comment by gwerbin** [comment]
Same problem here, too... except did you switch "expected" and "actual" behavior?

I'm on OS X 10.11.5

```
NyaoVim version 0.0.19
  electron : 0.36.12
  chrome : 47.0.2526.110
  node : 5.1.1
  v8 : 4.7.80.27
```

```
NVIM v0.1.5-800-gecbc9db
Build type: Release
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20160529-87005-2rt9sk/build/config -I/tmp/neovim-20160529-87005-2rt9sk/src -I/tmp/neovim-20160529-87005-2rt9sk/deps-build/usr/include -I/tmp/neovim-20160529-87005-2rt9sk/deps-build/usr/include -I/tmp/neovim-20160529-87005-2rt9sk/deps-build/usr/include -I/tmp/neovim-20160529-87005-2rt9sk/deps-build/usr/include -I/tmp/neovim-20160529-87005-2rt9sk/deps-build/usr/include -I/tmp/neovim-20160529-87005-2rt9sk/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20160529-87005-2rt9sk/build/src/nvim/auto -I/tmp/neovim-20160529-87005-2rt9sk/build/include
Compiled by greg@greg-macbook.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD/share/nvim"
```

**Comment by deto** [comment]
Yeah. Whoops.  Hope it's obvious from context

**Comment by gwerbin** [comment]
FWIW I see this error in the devloper console:

```
Uncaught TypeError: Cannot read property 'prototype' of undefined
```

**Comment by tjdevries** [comment]
I have the same problem, with the same error as noted by @gwerbin.

Has anyone found a solution to this? Maybe reverting to an older version of Neovim?

**Comment by gwerbin** [comment]
Any updates on this?

**Comment by gosukiwi** [comment]
Personally, the issue I had was related to my `.vimrc`. It was not compatible with neovim, it seems. It would be great to get an error message instead of just a blank screen though.

**Comment by gwerbin** [comment]
@gosukiwi I tried renaming/disabling both my `.vimrc` and `nvim/init.vim` files, still got a blank window.

**Comment by jonsmithers** [comment]
I'm getting this issue in Ubuntu. I was able to print a stacktrace:

```
TypeError: Cannot read property 'prototype' of undefined
    at generateWrappers (/home/smithers/.npm-global/lib/node_modules/nyaovim/node_modules/promised-neovim-client/index.js:75:13)
    at /home/smithers/.npm-global/lib/node_modules/nyaovim/node_modules/promised-neovim-client/index.js:189:13
    at Session._parse_message (/home/smithers/.npm-global/lib/node_modules/nyaovim/node_modules/msgpack5rpc/index.js:96:5)
    at Decoder.<anonymous> (/home/smithers/.npm-global/lib/node_modules/nyaovim/node_modules/msgpack5rpc/index.js:42:11)
    at emitOne (events.js:77:13)
    at Decoder.emit (events.js:169:7)
    at readableAddChunk (/home/smithers/.npm-global/lib/node_modules/nyaovim/node_modules/msgpack5/node_modules/readable-stream/lib/_stream_readable.js:210:18)
    at Decoder.Readable.push (/home/smithers/.npm-global/lib/node_modules/nyaovim/node_modules/msgpack5/node_modules/readable-stream/lib/_stream_readable.js:169:10)
    at Decoder.Transform.push (/home/smithers/.npm-global/lib/node_modules/nyaovim/node_modules/msgpack5/node_modules/readable-stream/lib/_stream_transform.js:123:32)
    at Decoder._transform (/home/smithers/.npm-global/lib/node_modules/nyaovim/node_modules/msgpack5/lib/streams.js:65:10)
```

**Comment by gwerbin** [comment]
@jonsmithers interesting, it's the same error but it looks like it's from a different location than mine.

**Comment by rhysd** [comment]
The error looks to occur here:

https://github.com/rhysd/promised-neovim-client/blob/03ede48e03ae4505290512acbbad4252dc591e19/index.js#L93

I'll try this on Windows8 machine (I don't have Windows10 machine).

**Comment by rhysd** [comment]
I reproduced this although the error message is not the same:

```
nvim.uiAttach is not a function
```

**Comment by rhysd** [comment]
I noticed `nvim` in my Windows environment is too old.  After updating `nvim` to 0.1.5-dev, it looks to be working well.

![default](https://cloud.githubusercontent.com/assets/823277/17547518/96a68826-5f22-11e6-964c-95b4bb1b0363.JPG)

I don't know this is Windows10 related issue or already this issue had gone because I can't reproduce.

**Comment by argentum47** [comment]
I am having the same problem on Debian Jessie, using nvim 0.1.1 .

**Comment by rhysd** [comment]
@argentum47 

Please upadte Neovim.  Currently `nvim` v0.1.5 is supported.

**Comment by htfy96** [comment]
Confirmed on my Arch Linux x64 with Gnome.
```
NyaoVim version 0.0.20
  electron : 1.3.4
  chrome : 52.0.2743.82
  node : 6.3.0
  v8 : 5.2.361.43
```

```
➜  ~ nvim -v
NVIM v0.1.6-27-g0b5a7e4
Build type: Dev
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -g -fvar-tracking-assignments -Wconversion -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/tmp/yaourt-tmp-lz/aur-neovim-git/src/neovim-git/build/config -I/tmp/yaourt-tmp-lz/aur-neovim-git/src/neovim-git/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/tmp/yaourt-tmp-lz/aur-neovim-git/src/neovim-git/build/src/nvim/auto -I/tmp/yaourt-tmp-lz/aur-neovim-git/src/neovim-git/build/include
Compiled by lz@lzPC

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

     System vimrc : "$VIM/sysinit.vim"
         $VIM preset: "/usr/share/nvim"
```

Run it with `gdb --args node /usr/bin/nyaovim --no-detach -u NONE` and pause it with C-Z, then `bt` outputs as follow:
```
(gdb) info threads 
  Id   Target Id         Frame 
* 1    Thread 0x7ffff7fb0740 (LWP 12617) "node" 0x00007ffff5707f19 in syscall () from /usr/lib/libc.so.6
  2    Thread 0x7ffff7ff7700 (LWP 12621) "node" 0x00007ffff73824f7 in do_futex_wait.constprop () from /usr/lib/libpthread.so.0
  3    Thread 0x7ffff398f700 (LWP 12622) "V8 WorkerThread" 0x00007ffff77aa330 in ?? () from /usr/lib/libuv.so.1
  4    Thread 0x7ffff318e700 (LWP 12623) "V8 WorkerThread" 0x00007ffff73824f7 in do_futex_wait.constprop () from /usr/lib/libpthread.so.0
  5    Thread 0x7ffff298d700 (LWP 12624) "V8 WorkerThread" 0x00007ffff73824f7 in do_futex_wait.constprop () from /usr/lib/libpthread.so.0
  6    Thread 0x7ffff218c700 (LWP 12625) "V8 WorkerThread" 0x00007ffff73824f7 in do_futex_wait.constprop () from /usr/lib/libpthread.so.0
(gdb) thread apply all bt

Thread 6 (Thread 0x7ffff218c700 (LWP 12625)):
#0  0x00007ffff73824f7 in do_futex_wait.constprop () from /usr/lib/libpthread.so.0
#1  0x00007ffff73825a4 in __new_sem_wait_slow.constprop.0 () from /usr/lib/libpthread.so.0
#2  0x0000000000e77b08 in v8::base::Semaphore::Wait() ()
#3  0x0000000000de1339 in v8::platform::TaskQueue::GetNext() ()
#4  0x0000000000de169c in v8::platform::WorkerThread::Run() ()
#5  0x0000000000e78e20 in ?? ()
#6  0x00007ffff737a454 in start_thread () from /usr/lib/libpthread.so.0
#7  0x00007ffff570c7df in clone () from /usr/lib/libc.so.6

Thread 5 (Thread 0x7ffff298d700 (LWP 12624)):
#0  0x00007ffff73824f7 in do_futex_wait.constprop () from /usr/lib/libpthread.so.0
#1  0x00007ffff73825a4 in __new_sem_wait_slow.constprop.0 () from /usr/lib/libpthread.so.0
#2  0x0000000000e77b08 in v8::base::Semaphore::Wait() ()
#3  0x0000000000de1339 in v8::platform::TaskQueue::GetNext() ()
#4  0x0000000000de169c in v8::platform::WorkerThread::Run() ()
#5  0x0000000000e78e20 in ?? ()
#6  0x00007ffff737a454 in start_thread () from /usr/lib/libpthread.so.0
#7  0x00007ffff570c7df in clone () from /usr/lib/libc.so.6

Thread 4 (Thread 0x7ffff318e700 (LWP 12623)):
#0  0x00007ffff73824f7 in do_futex_wait.constprop () from /usr/lib/libpthread.so.0
#1  0x00007ffff73825a4 in __new_sem_wait_slow.constprop.0 () from /usr/lib/libpthread.so.0
#2  0x0000000000e77b08 in v8::base::Semaphore::Wait() ()
#3  0x0000000000de1339 in v8::platform::TaskQueue::GetNext() ()
#4  0x0000000000de169c in v8::platform::WorkerThread::Run() ()
#5  0x0000000000e78e20 in ?? ()
#6  0x00007ffff737a454 in start_thread () from /usr/lib/libpthread.so.0
#7  0x00007ffff570c7df in clone () from /usr/lib/libc.so.6

Thread 3 (Thread 0x7ffff398f700 (LWP 12622)):
#0  0x00007ffff77aa330 in ?? () from /usr/lib/libuv.so.1
#1  <signal handler called>
#2  0x00007ffff73824f7 in do_futex_wait.constprop () from /usr/lib/libpthread.so.0
#3  0x00007ffff73825a4 in __new_sem_wait_slow.constprop.0 () from /usr/lib/libpthread.so.0
#4  0x0000000000e77b08 in v8::base::Semaphore::Wait() ()
#5  0x0000000000de1339 in v8::platform::TaskQueue::GetNext() ()
#6  0x0000000000de169c in v8::platform::WorkerThread::Run() ()
#7  0x0000000000e78e20 in ?? ()
#8  0x00007ffff737a454 in start_thread () from /usr/lib/libpthread.so.0
#9  0x00007ffff570c7df in clone () from /usr/lib/libc.so.6

---Type <return> to continue, or q <return> to quit---
Thread 2 (Thread 0x7ffff7ff7700 (LWP 12621)):
#0  0x00007ffff73824f7 in do_futex_wait.constprop () from /usr/lib/libpthread.so.0
#1  0x00007ffff73825a4 in __new_sem_wait_slow.constprop.0 () from /usr/lib/libpthread.so.0
#2  0x00007ffff77ae032 in uv_sem_wait () from /usr/lib/libuv.so.1
#3  0x0000000000d721a2 in node::DebugSignalThreadMain(void*) ()
#4  0x00007ffff737a454 in start_thread () from /usr/lib/libpthread.so.0
#5  0x00007ffff570c7df in clone () from /usr/lib/libc.so.6

Thread 1 (Thread 0x7ffff7fb0740 (LWP 12617)):
#0  0x00007ffff5707f19 in syscall () from /usr/lib/libc.so.6
#1  0x00007ffff77b2e0a in ?? () from /usr/lib/libuv.so.1
#2  0x00007ffff77b113d in ?? () from /usr/lib/libuv.so.1
#3  0x00007ffff77a2c44 in uv_run () from /usr/lib/libuv.so.1
#4  0x0000000000d71a70 in node::Start(int, char**) ()
#5  0x00007ffff5644291 in __libc_start_main () from /usr/lib/libc.so.6
#6  0x00000000006c7d3a in _start ()
```

It seems that this bug is probably caused by deadlock.

Single step result: 
[debug.log.zip](https://github.com/rhysd/NyaoVim/files/442731/debug.log.zip)

**Comment by Ginden** [comment]
I have the same issue.

```
ginden@ginden:~/Projects/node$ nvim -v

NVIM 0.1.6-dev
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim-cFoKmP/neovim-0.1.5ubuntu1+git201608291835+2734+21~ubuntu16.04.1/build/config -I/build/neovim-cFoKmP/neovim-0.1.5ubuntu1+git201608291835+2734+21~ubuntu16.04.1/src -I/build/neovim-cFoKmP/neovim-0.1.5ubuntu1+git201608291835+2734+21~ubuntu16.04.1/.deps/usr/include -I/build/neovim-cFoKmP/neovim-0.1.5ubuntu1+git201608291835+2734+21~ubuntu16.04.1/.deps/usr/include -I/build/neovim-cFoKmP/neovim-0.1.5ubuntu1+git201608291835+2734+21~ubuntu16.04.1/.deps/usr/include -I/build/neovim-cFoKmP/neovim-0.1.5ubuntu1+git201608291835+2734+21~ubuntu16.04.1/.deps/usr/include -I/build/neovim-cFoKmP/neovim-0.1.5ubuntu1+git201608291835+2734+21~ubuntu16.04.1/.deps/usr/include -I/build/neovim-cFoKmP/neovim-0.1.5ubuntu1+git201608291835+2734+21~ubuntu16.04.1/.deps/usr/include -I/usr/include -I/build/neovim-cFoKmP/neovim-0.1.5ubuntu1+git201608291835+2734+21~ubuntu16.04.1/build/src/nvim/auto -I/build/neovim-cFoKmP/neovim-0.1.5ubuntu1+git201608291835+2734+21~ubuntu16.04.1/build/include
Compiled by buildd@lgw01-41

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

Nyaovim package.json:

```
  "_id": "nyaovim@0.0.20",
  "_resolved": "https://registry.npmjs.org/nyaovim/-/nyaovim-0.0.20.tgz",
```

System info:

```
                          ./+o+-       ginden@ginden
                  yyyyy- -yyyyyy+      OS: Ubuntu 16.04 xenial
               ://+//////-yyyyyyo      Kernel: x86_64 Linux 4.4.0-34-generic
           .++ .:/++++++/-.+sss/`      Uptime: 14m
         .:++o:  /++++++++/:--:/-      Packages: 1950
        o:+o+:++.`..```.-/oo+++++/     Shell: bash 4.3.46
       .:+o:+o/.          `+sssoo+/    Resolution: 1920x1200
  .++/+:+oo+o:`             /sssooo.   DE: Unity 7.4.0
 /+++//+:`oo+o               /::--:.   WM: Compiz
 \+/+o+++`o++o               ++////.   WM Theme: Ambiance
  .++.o+++oo+:`             /dddhhh.   GTK Theme: Ambiance [GTK2/3]
       .+.o+oo:.          `oddhhhh+    Icon Theme: ubuntu-mono-dark
        \+.++o+o``-````.:ohdhhhhh+     Font: Ubuntu 11
         `:o+++ `ohhhhhhhhyo++os:      CPU: Intel Core i5-6600 CPU @ 3.9GHz
           .o:`.syhhhhhhh/.oo++o`      GPU: GeForce GTX 960
               /osyyyyyyo++ooo+++/     RAM: 1765MiB / 16000MiB
                   ````` +oo+++o\:    
                          `oo++.      

```

Issue persist with nyaovim 0.0.18, 0.0.16, 0.0.14.

**Comment by israelg99** [comment]
Same issue with Kubuntu 16.04.
Any solutions yet? I'll try to investigate further.

**Comment by crazymanjinn** [comment]
Seeing the same behavior. It's also interesting that if I launch `nyaovim` with `NODE_ENV=debug`, the devtools window doesn't pop-up. If I roll-back to nyaovim 0.0.20, the devtools do pop-up although the blank window behavior is the exact same.

    nvim --version
    NVIM v0.1.6-93-g7eb4d2f
    Build type: Release
    Compilation: /usr/local/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20160913-59962-1yxmdyt/build/config -I/tmp/neovim-20160913-59962-1yxmdyt/src -I/tmp/neovim-20160913-59962-1yxmdyt/deps-build/usr/include -I/tmp/neovim-20160913-59962-1yxmdyt/deps-build/usr/include -I/tmp/neovim-20160913-59962-1yxmdyt/deps-build/usr/include -I/tmp/neovim-20160913-59962-1yxmdyt/deps-build/usr/include -I/tmp/neovim-20160913-59962-1yxmdyt/deps-build/usr/include -I/tmp/neovim-20160913-59962-1yxmdyt/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20160913-59962-1yxmdyt/build/src/nvim/auto -I/tmp/neovim-20160913-59962-1yxmdyt/build/include
    Compiled by daniel.samplin@DSamplinerDUR-MBP.local
    
    Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
    For differences from Vim, see :help vim-differences
    
       system vimrc file: "$VIM/sysinit.vim"
      fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-7eb4d2f/share/nvim"

    nyaovim --version
    NyaoVim version 0.0.21
      electron : 1.3.5
      chrome : 52.0.2743.82
      node : 6.3.0
      v8 : 5.2.361.43

**Comment by fsworld009** [comment]
Same issue with nvim 0.1.6 and nyaovim 0.0.21 under Windows 7 x64
I also tried leaving init.vim as blank but it didn't help.
neovim-qt works in my environment, so I believe nvim is installed correctly.

```
C:\>nvim -v
NVIM v0.1.6-833-g35f67ee
Build type: Release
Compilation: C:/msys64/mingw64/bin/gcc.exe -Wconversion -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -D__USE_MINGW_ANSI_STDIO -D_WIN32_WINNT=0x0600 -Wvla -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/msys64/mingw64/include -IC:/msys64/mingw64/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appvyr-winppveyor@APPVYR-WIN

Optional features included (+) or not (-): -acl   +iconv    -jemalloc -tui

For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"
```

```
C:\>nyaovim --version

NyaoVim version 0.0.21
  electron : 1.4.0
  chrome : 53.0.2785.113
  node : 6.5.0
  v8 : 5.3.332.45
```

**Comment by fsworld009** [comment]
Same issue with Mac OSX 10.11.6 + neovim 0.1.5
Removing init.vim didn't help, either.
```
$  nvim -v
NVIM 0.1.5
Build type: RelWithDebInfo
Compilation: /usr/local/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20160916-38433-p43n66/neovim-0.1.5/build/config -I/tmp/neovim-20160916-38433-p43n66/neovim-0.1.5/src -I/tmp/neovim-20160916-38433-p43n66/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20160916-38433-p43n66/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20160916-38433-p43n66/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20160916-38433-p43n66/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20160916-38433-p43n66/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20160916-38433-p43n66/neovim-0.1.5/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include -I/tmp/neovim-20160916-38433-p43n66/neovim-0.1.5/build/src/nvim/auto -I/tmp/neovim-20160916-38433-p43n66/neovim-0.1.5/build/include
Compiled by fsworld009@fsworld009-MacBook-Pro.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.1.5/share/nvim"
```

```
$  nyaovim --version
NyaoVim version 0.0.21
  electron : 1.4.0
  chrome : 53.0.2785.113
  node : 6.5.0
  v8 : 5.3.332.45
```

**Comment by fsworld009** [comment]
Reverting nyaovim to 0.0.20, both Windows 7 and Mac environment work now.
For anyone who wants to revert, do

```
npm uninstall -g nyaovim
npm install -g nyaovim@0.0.20
```

**Comment by rhysd** [comment]
@fsworld009 

Correct.  NyaoVim now works well with `nvim` HEAD. Please update `nvim`.  This is because `nvim` v0.1.6 has some msgpack UI RPC API updates.  NyaoVim doesn't support `nvim` v0.1.5 because NyaoVim considers that clean code is more important than backward compatibility until nvim v1.0 is released.  

If you have some reason not to use nvim HEAD, please continue to use NyaoVim v0.0.20 until nvim v0.1.6 stable is released.

**Comment by htfy96** [comment]
Fixed after upgrading nyaovim from 0.0.20 to 0.0.21.
It seems that only 0.0.20 + nvim0.1.5 & 0.0.21 + nvim 0.1.6 work fine.

**Comment by rhysd** [comment]
@htfy96 

yeah, NyaoVim 0.0.21 does not support nvim v0.1.6.  It's expected behavior.

**Comment by szsdk** [comment]
Still have problem with 0.021 + nvim 0.1.6
```
NyaoVim version 0.0.21
  electron : 1.4.0
  chrome : 53.0.2785.113
  node : 6.5.0
  v8 : 5.3.332.45
```

`NVIM 0.1.6-dev`

**Comment by rhysd** [comment]
Could you see the console in DevTools?

And your output says Electron version is 1.4.0.  I'm specifying [v1.3.5 in package.json](https://github.com/rhysd/NyaoVim/blob/master/package.json#L46).  Did you install 'electron' or 'electron-prebuilt' package by your hand?

**Comment by fsworld009** [comment]
According to [package.json doc](https://docs.npmjs.com/files/package.json), "^1.3.5" means  "Compatible with version 1.3.5". Not sure how this condition is checked but I think v1.4.0 is counted as compatible here. So if the application depends on 1.3.5 only you might want to change your package.json to
> "electron-prebuilt": "1.3.5"

to force v1.3.5.

**Comment by szsdk** [comment]
@rhysd Sorry, I don't know how to use the DevTools. I'm totally newbie here. Maybe I can learn it latter.

I didn't install it by hand. I use your command
```
sudo npm install -g nyaovim
```
And my system is Ubuntu 14.04.

**Comment by rhysd** [comment]
@fsworld009 

Oh, I need to specify `~1.3.5` but actually `^1.3.5`...  Thanks.


@szsdk 

1. Please open DevTools window with 'Menu' -> 'View' -> 'Open Developer Tools'
2. Find 'console' tab and click it, then the message log will be shown in the pane.

**Comment by rhysd** [comment]
I still can't reproduce this with MacBook Pro or iMac or MacBook Air...

Can anyone help with below command?

```
$ NODE_ENV=debug nyaovim -u NONE --no-detach
```

It does reproduce this?  If so, is anything output in shell, in console in DevTools or in dialog?

**Comment by szsdk** [comment]
@rhysd 
It shows 
`DevTools was disconnected from the page.`
And there is nothing showed in console.

**Comment by deathmaz** [comment]
```sh
$ nyaovim --version
NyaoVim version 0.0.21
  electron : 1.4.1
  chrome : 53.0.2785.113
  node : 6.5.0
  v8 : 5.3.332.45
```

After this command:
`$ NODE_ENV=debug nyaovim -u NONE --no-detach`
White screen in NyaoVim,
no output in console,
`DevTools was disconnected from the page.` when i switch to DevTools,
empty DevTools console.

**Comment by jordwalke** [comment]
I followed the instructions (and I have nvim `0.1.6`) and after installing I got:

```
NyaoVim version 0.0.21
  electron : 1.4.1
  chrome : 53.0.2785.113
  node : 6.5.0
  v8 : 5.3.332.45
```

Which doesn't work. Could you please update the README with instructions about specific combinations that work? I think it's okay to move forward and not worry about backwards compat, as long as the specific versions are documented.


And if you need version `1.3.5`, it should be specified as such in the `package.json` right?

**Comment by jordwalke** [comment]
Did that diff fix the issue? On Mac?

**Comment by rhysd** [comment]
@jordwalke I'm sorry, I mistook the issue number... It was for #57.

**Comment by raacker** [comment]
@rhysd I tried on 
`$ NODE_ENV=debug nyaovim -u NONE --no-detach`

and 

`Uncaught TypeError : Cannot read property 'prototype' of undefined ` occurred! as I saw above.

I'm using Linux-mint and tried to roll-back to 0.0.20

`Nyaovim version 0.0.20
   electron : 1.4.1
   chrome : 53.0.2785.113
   node : 6.5.0
   v8 : 5.3.332.45`

**Comment by rhysd** [comment]
@raacker I guess you're using `nvim` v0.1.5.  NyaoVim 0.0.21 supports `nvim` v0.1.6 only.  Please update `nvim`.  As you said, API was changed while v0.1.5 -> v0.1.6.

**Comment by raacker** [comment]
Nope... unfortunately, I'm using nvim 0.1.6... 

`NVIM v0.1.6-143-g68bcb32`

**Comment by rhysd** [comment]
@raacker 

Hmm... when did you build `nvim`?  It seems that API changes were added after version bumping.  

I updated my `nvim` with `brew install --HEAD neovim --with-release` today and it works. Could you check with the latest `nvim`?  My `nvim --version` says:

```
NVIM v0.1.6-104-g22dfe69
Build type: Release
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20160928-3886-13no3u/build/config -I/tmp/neovim-20160928-3886-13no3u/src -I/tmp/neovim-20160928-3886-13no3u/deps-build/usr/include -I/tmp/neovim-20160928-3886-13no3u/deps-build/usr/include -I/tmp/neovim-20160928-3886-13no3u/deps-build/usr/include -I/tmp/neovim-20160928-3886-13no3u/deps-build/usr/include -I/tmp/neovim-20160928-3886-13no3u/deps-build/usr/include -I/tmp/neovim-20160928-3886-13no3u/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20160928-3886-13no3u/build/src/nvim/auto -I/tmp/neovim-20160928-3886-13no3u/build/include
Compiled by rhysd

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

      システム vimrc: "$VIM/sysinit.vim"
       省略時の $VIM: "/usr/local/Cellar/neovim/HEAD-22dfe69/share/nvim"

```

**Comment by raacker** [comment]
I cloned neovim and built it. 
```
NVIM v0.1.6-143-g68bcb32
Build type: Debug
Compilation: /usr/bin/cc -Wconversion -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector --param ssp-buffer-size=4 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/home/haven/neovim/build/config -I/home/haven/neovim/src -I/home/haven/neovim/.deps/usr/include -I/home/haven/neovim/.deps/usr/include -I/home/haven/neovim/.deps/usr/include -I/home/haven/neovim/.deps/usr/include -I/home/haven/neovim/.deps/usr/include -I/home/haven/neovim/.deps/usr/include -I/usr/include -I/home/haven/neovim/build/src/nvim/auto -I/home/haven/neovim/build/include
Compiled by root@Havenmachine

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

```

Do I have to use brew instead of build it myself?

**Comment by raacker** [comment]
Ah... maybe it is not for Release type... :) I'll try on release version! Thanks !

**Comment by raacker** [comment]
Just for comment, I found that in [Index.js](https://github.com/rhysd/promised-neovim-client/blob/03ede48e03ae4505290512acbbad4252dc591e19/index.js#L51), typeName was Nvim and the target string was Vim. And also, === operator returned false to it! I think it needs to be considered for future neovim version. That would be the key of newer API

**Comment by jordwalke** [comment]
I tried `HEAD` `nvim` yesterday, and `npm install nyaovim` and it still doesn't work on `Mac`. Could it be the electron version?

```
NyaoVim version 0.0.21
  electron : 1.4.1
  chrome : 53.0.2785.113
  node : 6.5.0
  v8 : 5.3.332.45
```

```
NVIM 0.1.6-dev
```

I followed the instructions and it doesn't work. I'm eagerly waiting to try this app.

**Comment by rhysd** [comment]
@jordwalke I also tried with the same version of NyaoVim, Electron and `nvim` on iMac (non-Retina) and MacBook Pro (Retina), then I still can't reproduce this issue...

**Comment by jordwalke** [comment]
Tried again by installing the release version of 0.1.6 nvim and it still didn't work :(

```
NVIM v0.1.6-144-g22dfe69
Build type: Release
```

What version of electron do you have? `1.4.1`?

**Comment by rhysd** [comment]
@jordwalke Yes, as I commented in above, my `nvim --version` and `nyaovim --version` are

- `nvim --version`

```
NVIM v0.1.6-104-g22dfe69
Build type: Release
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20160928-3886-13no3u/build/config -I/tmp/neovim-20160928-3886-13no3u/src -I/tmp/neovim-20160928-3886-13no3u/deps-build/usr/include -I/tmp/neovim-20160928-3886-13no3u/deps-build/usr/include -I/tmp/neovim-20160928-3886-13no3u/deps-build/usr/include -I/tmp/neovim-20160928-3886-13no3u/deps-build/usr/include -I/tmp/neovim-20160928-3886-13no3u/deps-build/usr/include -I/tmp/neovim-20160928-3886-13no3u/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20160928-3886-13no3u/build/src/nvim/auto -I/tmp/neovim-20160928-3886-13no3u/build/include
Compiled by rhysd

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

      システム vimrc: "$VIM/sysinit.vim"
       省略時の $VIM: "/usr/local/Cellar/neovim/HEAD-22dfe69/share/nvim"
```

- `nyaovim --version`

```
NyaoVim version 0.0.21
  electron : 1.4.1
  chrome : 53.0.2785.113
  node : 6.5.0
  v8 : 5.3.332.45
```

**Comment by raacker** [comment]
I think there's an issue between 0.1.6-104 to 0.1.6-14x. That's only different

**Comment by rhysd** [comment]
Let me organize 'white screen' issue here.  There are two kinds of error in this issue.

- Renderer process does not work
  - DevTools can't be launched because renderer is not running
  - This is a main issue of this issue (@jordwalke and others reported)
- `Cannot read property 'prototype'` error
  - DevTools reports an error in console
  - It occurs because of Neovim's msgpack UI API
  - @raacker reported

**Comment by rhysd** [comment]
I took a screencast gif.  As below, it works in my environment...

![tmp](https://cloud.githubusercontent.com/assets/823277/18903428/088a65c4-8594-11e6-9754-41b6a9eec384.gif)

**Comment by raacker** [comment]
Okay! I'l work on it today and if it still has that issue, I'll create one :) Thank you!

**Comment by rhysd** [comment]
@raacker Thank you so much for your confirmation.  So some v0.1.6 doesn't work and need to be updated to the latest... I understood :smile:

**Comment by jordwalke** [comment]
@rhysd  Yeah, I have the exact same `nvim` version as you `v0.1.6-144-g22dfe69 release`, and same electron, nyaovim version too. Another interesting thing, when I open up nyaovim, I see an error message in the Chrome log that I did not see reported here:

```
Failed to clear temp storage: It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources. SecurityError
```

**Comment by rhysd** [comment]
Oh, I didn't get the log.  It may be the root cause.  Could you please try below?

1. `$ rm ~/Library/Application\ Support/Nyaovim`
2. Start NyaoVim

**Comment by jordwalke** [comment]
That got rid of that message, thanks. It did not get rid of the white screen problem though.

**Comment by jordwalke** [comment]
How do I try a different version of Electron to see if it works?

**Comment by rhysd** [comment]
> It did not get rid of the white screen problem though.

Thank you for your try.  Hmm... `$ELECTRON_ENABLE_LOGGIN` may be helpful.  Could you try below?

```
$ ELECTRON_ENABLE_LOGGIN=yes NODE_ENV=debug nyaovim -u NONE
```

It may dump many logs to stderr.

> How do I try a different version of Electron to see if it works?

I guess:

1. `$ rm -r ~/Library/Application\ Support/Nyaovim` and ensure that nayovim is uninstalled.
2. `$ npm install -g electron-prebuilt@x.y.z` (x.y.z is a version number you want to use)
3. `$ npm install -g nyaovim`

**Comment by jordwalke** [comment]
`ELECTRON_ENABLE_LOGGIN=yes NODE_ENV=debug nyaovim -u NONE` did not help either. I will try to install electro 3.5.1

**Comment by rhysd** [comment]
> ELECTRON_ENABLE_LOGGIN=yes NODE_ENV=debug nyaovim -u NONE did not help either.

You mean no log is output to stderr?

> I will try to install electro 3.5.1

Maybe 1.3.5? :smiley:

**Comment by jordwalke** [comment]
Tried with `1.3.5` and it did not work. Btw: You can't just globally install prebuilt electron, and then install nyaovim, expecting it to use your globally installed version. I had to go into the nyaovim node_modules directory and install 1.3.5 manually. Still did not work. I'm really frustrated because I want to use NyaoVim :D

**Comment by sinkuu** [comment]
I'm experiencing this problem, but DevTools can be launched and no errors at all in its console.
Using nvim `v0.1.6-175-g7246750` and nyaovim `0.0.21` with electron `1.4.1`.

> Thank you for your try. Hmm... $ELECTRON_ENABLE_LOGGIN may be helpful. Could you try below?
> 
> `$ ELECTRON_ENABLE_LOGGIN=yes NODE_ENV=debug nyaovim -u NONE`

Isn't the correct env var is `ELECTRON_ENABLE_LOGGING`? https://github.com/electron/electron/blob/master/docs/api/environment-variables.md

Still no helpful logs on my mechine though.

```bash
$ ELECTRON_ENABLE_LOGGING=true NODE_ENV=debug nyaovim --no-detach
[7500:0929/113819:ERROR:browser_main_loop.cc(239)] GTK theme error: Unable to locate theme engine in module_path: "murrine",
```

 (This error message seems unrelated - installing `murrine` theme resolves it and still getting a blank window)

**Comment by rhysd** [comment]
@jordwalke 

Thank you for confirmation. Hmm... So it's not dependent on Electron version. Anyway, we need to solve this for Electron v1.4.1 because we can't stay in v1.3 to catch up the latest Electron updates.

@sinkuu 

Thank you for confirmation.

> Isn't the correct env var is ELECTRON_ENABLE_LOGGING?

Oh, you're absolutely right.

```
$ ELECTRON_ENABLE_LOGGING=yes NODE_ENV=debug nyaovim -u NONE --no-detach
```

is correct to gather all debug information for now.

**Comment by sinkuu** [comment]
I inserted `console.log` here and there, and found that the nyaovim stalled at [this line](https://github.com/rhysd/NyaoVim/blob/3b111aeef65366361b65580b92d30975978497ce/main/main.ts#L120):

```typescript
if (browser_config.loaded_config.show_menubar === false) { // <===
        win.setMenuBarVisibility(false);
}
```

So the problem (on my machine, probably) is the configuration not loaded or something. I tried

```bash
$ echo '{}' > ~/.config/nyaovim/browser-config.json
```

and NyaoVim worked :smile:

**Comment by rhysd** [comment]
@sinkuu 

Nice! Thank you so much for your debug.
I also could reproduce this when removing `browser-config.json`.

I'll fix this issue and release nyaovim v0.0.22 tonight!

**Comment by jordwalke** [comment]
Hey, with my setup above (latest everything including nvim, electron, nyaovim) the `browser-config.json` fix worked! It still flashes a white screen, but it automatically goes away and loads my colorscheme. Should I file an issue for nyaovim to avoid the ugly white screen (so you can customize the loading color instead of white to match your colorscheme? (even if hardcoded in `browser-config.json`)

**Comment by rhysd** [comment]
> It still flashes a white screen

You mean that white screen at first, then it shows the screen after enter key?  If so, I guess some messages are echoed by `nvim` (please check `:message`).  Because of Neovim's UI architecture, it's not possible to get messages echoed before process attaching to UI API.

**Comment by jordwalke** [comment]
> You mean that white screen at first, then it shows the screen after enter key? 

I don't even have to press enter. I just wait a second and the white screen goes away.

**Comment by rhysd** [comment]
I think it's just a loading time.  Electron is a customized Chromium browser.  So it takes a bit to start up renderer process. In addition, NyaoVim spawn `nvim` process and attaches to the process for msgpack API.  After all UI events are sent from `nvim`, NyaoVim finally paints UI to the screen.

**Comment by jordwalke** [comment]
Yeah, I'm not super bothered by it. But it *would* be nice to be able to customize the color of the screen eventually (you could even read the bg color of the colorscheme at last application-quit time, and use that for the bg color at startup time while waiting for Chromium to load).

**Comment by rhysd** [comment]
NyaoVim's entry point is a HTML file (`~/.config/nyaovim/nyaovimrc.html`).  So at least we can change its background color with CSS before `nvim` process starts (although JavaScript is needed to obtain fg/bg colors of screen).

**Comment by rhysd** [comment]
I fixed this bug and published new version of NyaoVim.  Please update and confirm the fix.

Thank you so much for reporting, confirming and debugging :smile:

**Comment by deathmaz** [comment]
Confirmed, it works on Linux `NVIM v0.1.6-175-g7246750`
Thank you!

**Comment by szsdk** [comment]
It works on
```
NyaoVim version 0.0.22
  electron : 1.4.1
  chrome : 53.0.2785.113
  node : 6.5.0
  v8 : 5.3.332.45
```

**Comment by raacker** [comment]
Wow... It really works! Thanks you for everyone in here :p
